kind = "DojoContract"
class_hash = "0x3ea068c930a55765223e357778a6265b56b93e654d27a2849d8efe895244cf2"
original_class_hash = "0x3ea068c930a55765223e357778a6265b56b93e654d27a2849d8efe895244cf2"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-actions"
systems = [
    "flip",
    "flop",
]
manifest_name = "flippyflop-actions-4407e5f5"
