kind = "DojoContract"
class_hash = "0x7cd25945ea14b7d237c2f350e9f786a85e75e9798182bf62fa5c65c54f683a0"
original_class_hash = "0x7cd25945ea14b7d237c2f350e9f786a85e75e9798182bf62fa5c65c54f683a0"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-actions"
systems = [
    "flip",
    "flop",
    "claim",
]
manifest_name = "flippyflop-actions-4407e5f5"
