kind = "DojoContract"
class_hash = "0x24960c72dd6fb3d8236a475f0f087744c4007ec5da1ceb174fb63147e265a7a"
original_class_hash = "0x24960c72dd6fb3d8236a475f0f087744c4007ec5da1ceb174fb63147e265a7a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "flippyflop-actions"
manifest_name = "flippyflop-actions-4407e5f5"
