kind = "DojoContract"
class_hash = "0x11e09a4a1d7743c87ec44155bb76f25afac2a33d6870ec108ccde1930aee12c"
original_class_hash = "0x11e09a4a1d7743c87ec44155bb76f25afac2a33d6870ec108ccde1930aee12c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-actions"
systems = [
    "flip",
    "flop",
    "claim",
]
manifest_name = "flippyflop-actions-4407e5f5"
