kind = "DojoContract"
class_hash = "0x192db261dca4aa58ce197a2947f7b0af929b582fe317688f67c19941b41e1a3"
original_class_hash = "0x192db261dca4aa58ce197a2947f7b0af929b582fe317688f67c19941b41e1a3"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-game-23e1ad43.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-game"
systems = [
    "lock",
    "unlock",
]
manifest_name = "flippyflop-game-23e1ad43"
