kind = "DojoContract"
class_hash = "0x5728ae47027cc1a450ef87fa6388d2dd47ef198f3521b85bee7be955c838802"
original_class_hash = "0x5728ae47027cc1a450ef87fa6388d2dd47ef198f3521b85bee7be955c838802"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-actions"
manifest_name = "flippyflop-actions-4407e5f5"
