[package]
cairo-version = "=2.7.0"
name = "flippyflop"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { path = "/Users/nasr/Documents/development.nosync/dojo/crates/dojo-core" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[profile.dev]
[profile.sepolia]
