[world]
kind = "WorldContract"
class_hash = "0x215f0e85953fb8a60ac54211eaa2368eaa5cda3427ca4eeb17078099d09a43d"
original_class_hash = "0x215f0e85953fb8a60ac54211eaa2368eaa5cda3427ca4eeb17078099d09a43d"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x1ca8e3b7bc101ffd443a1e3b452a4f49607841461b168cb2cc365322722b67"
transaction_hash = "0xbf63131ca74cb8d3edac57de7678de1b49e649c6aeb5fc92ee4898446dd60"
block_number = 3
seed = "flippyflop"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x6dc710c0589d8ceb1a924c6632f4c9a8623f85c38a7e0cbed845157727b9b54"
class_hash = "0x5728ae47027cc1a450ef87fa6388d2dd47ef198f3521b85bee7be955c838802"
original_class_hash = "0x5728ae47027cc1a450ef87fa6388d2dd47ef198f3521b85bee7be955c838802"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/flippyflop-actions-4407e5f5.json"
reads = []
writes = ["flippyflop-Tile"]
init_calldata = []
tag = "flippyflop-actions"
manifest_name = "flippyflop-actions-4407e5f5"

[[models]]
kind = "DojoModel"
class_hash = "0x7824b845296994a22d3df72db34fdea9f7aeec2fb0487459a07574ffe57549e"
original_class_hash = "0x7824b845296994a22d3df72db34fdea9f7aeec2fb0487459a07574ffe57549e"
abi = "manifests/dev/deployment/abis/models/flippyflop-Tile-61fb9291.json"
tag = "flippyflop-Tile"
manifest_name = "flippyflop-Tile-61fb9291"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "flipped"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3b76de62f8e30048590802eb9b8a74235bc6456dcdf04d086df0321ff91c909"
original_class_hash = "0x3b76de62f8e30048590802eb9b8a74235bc6456dcdf04d086df0321ff91c909"
abi = "manifests/dev/deployment/abis/models/flippyflop-User-25ca4606.json"
tag = "flippyflop-User"
manifest_name = "flippyflop-User-25ca4606"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "last_message"
type = "ByteArray"
key = false

[[models.members]]
name = "hovering_tile_x"
type = "u32"
key = false

[[models.members]]
name = "hovering_tile_y"
type = "u32"
key = false
