kind = "DojoContract"
class_hash = "0x7c94aef06e9d76934f52e2abaa8e990dd530472a0e554ef916266acb628c946"
original_class_hash = "0x7c94aef06e9d76934f52e2abaa8e990dd530472a0e554ef916266acb628c946"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/flippyflop-Flip-6bd3ed9d.json"
reads = []
writes = []
init_calldata = []
tag = "flippyflop-Flip"
systems = [
    "initializer",
    "mint_from",
    "burn_from",
]
manifest_name = "flippyflop-Flip-6bd3ed9d"
