kind = "DojoModel"
class_hash = "0x223db7359762f6103fbdf6e05b5756c3a1a1daa8d80c782894ee506c6293491"
original_class_hash = "0x223db7359762f6103fbdf6e05b5756c3a1a1daa8d80c782894ee506c6293491"
abi = "manifests/dev/base/abis/models/flippyflop-ERC20AllowanceModel-55d0c41e.json"
tag = "flippyflop-ERC20AllowanceModel"
qualified_path = "flippyflop::tokens::flip::erc_20_allowance_model"
manifest_name = "flippyflop-ERC20AllowanceModel-55d0c41e"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "spender"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u256"
key = false
