kind = "DojoModel"
class_hash = "0x4625d48c8f7e13db2ae84c89787171f8fa53752228ae147d3c50c8b327afab3"
original_class_hash = "0x4625d48c8f7e13db2ae84c89787171f8fa53752228ae147d3c50c8b327afab3"
abi = "manifests/dev/base/abis/models/flippyflop-ERC20MetadataModel-1fc3dc07.json"
tag = "flippyflop-ERC20MetadataModel"
qualified_path = "flippyflop::tokens::flip::erc_20_metadata_model"
manifest_name = "flippyflop-ERC20MetadataModel-1fc3dc07"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "symbol"
type = "ByteArray"
key = false

[[members]]
name = "decimals"
type = "u8"
key = false

[[members]]
name = "total_supply"
type = "u256"
key = false
