kind = "DojoModel"
class_hash = "0x7824b845296994a22d3df72db34fdea9f7aeec2fb0487459a07574ffe57549e"
original_class_hash = "0x7824b845296994a22d3df72db34fdea9f7aeec2fb0487459a07574ffe57549e"
abi = "manifests/dev/base/abis/models/flippyflop-Tile-61fb9291.json"
tag = "flippyflop-Tile"
manifest_name = "flippyflop-Tile-61fb9291"

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "flipped"
type = "felt252"
key = false
